site_name: 'Minha Documentação'
site_description: 'Exercício 2 de documentação'

nav:
- Início: index.md
- Sobre: nov.md

theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'pink'

plugins:
  - search
  - advanced-seo
  - pdf-export